[package]
name = "chan"
version = "0.1.0"
edition = "2021"

[dependencies]
strum = "0.26.3"
strum_macros = "0.26.4"
chrono = "0.4"
num-derive = "0.4"
num-traits = "0.2"
serde = "1.0"
serde_json = "1.0"
maybe_atomic_refcell = "0.3"
csv="1.3.0"